[project]
name = "data-engineering-repo-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=46.0.3",
    "marimo>=0.19.1",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "polars>=1.36.1",
    "psycopg[binary]>=3.3.2",
    "pyarrow>=22.0.0",
    "pypdf>=6.6.0",
    "pyzmq>=27.1.0",
    "reportlab>=4.4.7",
]
